config/routes.rb
Rails.application.routes.draw do
  resources :foos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foo.rb
class Foo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  before_action :set_foo, only: %i[ show edit update destroy ]

  # This analog would replace the `add_csp_exceptions` pattern.
  content_security_policy only: [:index] do |config|
    config.connect_src ->() do
      # look at me! I'm in an "action" context here.
      # so I can see cookies, the request, flipper, etc.

      # if current_user.foo?
      SecureRandom.hex(16) + ".com"
      # end
    end
  end

  # GET /foos or /foos.json
  def index
    # media source was not defined, so it needs to inherit what was in default-src
    append_content_security_policy_directives(media_src: %w(foo.com))

    # worker source is set to none, so we need to override that value
    append_content_security_policy_directives(worker_src: %w(foo.com))

    # results in
    # font-src 'self' https: data:;
    # img-src 'self' https: data:;
    # object-src 'none';
    # script-src 'self' https:;
    # style-src 'self' https:;
    # connect-src e84084ace36797dfa21d0ad79c9fcde8.com; <- set in the content_security_policy block above
    # default-src 'self' https:;
    # media-src 'self' https: foo.com; <- inherited default src
    # worker-src foo.com <- overrode none
    @foos = Foo.all
  end

  def append_content_security_policy_directives(directives)
    current_policy = current_content_security_policy
    directives.each do |directive, source_values|
      config = current_policy.send(directive)
      if config.nil?
        config = []
        config = current_policy.default_src
      end
      config = [] if config == %w('none')
      request.content_security_policy.send(directive, *(config + source_values))
    end
  end

  # GET /foos/1 or /foos/1.json
  def show
  end

  # GET /foos/new
  def new
    @foo = Foo.new
  end

  # GET /foos/1/edit
  def edit
  end

  # POST /foos or /foos.json
  def create
    @foo = Foo.new(foo_params)

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: "Foo was successfully created." }
        format.json { render :show, status: :created, location: @foo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foos/1 or /foos/1.json
  def update
    respond_to do |format|
      if @foo.update(foo_params)
        format.html { redirect_to @foo, notice: "Foo was successfully updated." }
        format.json { render :show, status: :ok, location: @foo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1 or /foos/1.json
  def destroy
    @foo.destroy
    respond_to do |format|
      format.html { redirect_to foos_url, notice: "Foo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foo_params
      params.fetch(:foo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/views/foos/_form.html.erb
<%= form_with(model: foo) do |form| %>
  <% if foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
        <% foo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>